[package]
name = "noodle"
version = "0.1.0"
authors = ["Félix Saparelli <felix@passcod.name>"]
edition = "2018"

[dependencies]
argh = "0.1.4"
async-std = { version = "1.9.0", features = ["attributes"] }
color-eyre = { version = "0.5.10", default-features = false }
ipnetwork = "0.17.0"
pnet = "0.27.2"
futures = "0.3.13"

[dependencies.rtnetlink]
version = "0.7.0"
git = "https://github.com/little-dude/netlink"
default-features = false
features = ["smol_socket"]

[profile.dev.package.backtrace]
opt-level = 3
