on:
  push:
    tags:
      - v*.*.*

name: Release

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - armv7-unknown-linux-gnueabihf
          - armv7-unknown-linux-musleabihf
          - riscv32gc-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        name: Build
        with:
          use-cross: ${{ matrix.target != 'x86_64-unknown-linux-gnu' }}
          command: build
          args: --release --target ${{ matrix.target }}
      - name: Package
        run: |
          set -eux
          bin="target/${{ matrix.target }}/release/noodle"
          version=$(echo "${{ github.ref }}" | cut -d/ -f3)
          dst="noodle-${version}-${{ matrix.target }}"
          mkdir "$dst"
          strip "$bin" || true
          mv "$bin" "$dst/"
          mv README.md COPYRIGHT LICENSE-MIT LICENSE-APACHE "$dst/"
          tar cavf "$dst.tar.xz" "$dst"
      - uses: softprops/action-gh-release@v1
        with:
          files: *.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
